plugins:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "sorbet/**/*"
    - "bin/**/*"
  Include:
    - "bin/runner"
  DisabledByDefault: true

Lint:
  Enabled: true
Sorbet:
  Enabled: true
